# Generated by Django 6.0.3 on 2026-05-18 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='observationmodel',
            name='img_thumbnail',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
