# Generated by Django 6.0 on 2026-03-19 00:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observationmodel',
            name='species',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obsertvations', to='api.speciesmodel', verbose_name='species'),
        ),
    ]
