# Generated by Django 6.0.3 on 2026-05-20 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_is_verified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speciesmodel',
            name='name',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
