# Generated by Django 6.0.3 on 2026-04-24 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_observationmodel_species'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observationmodel',
            name='img',
            field=models.ImageField(default='', upload_to='observations/'),
        ),
    ]
