# Generated by Django 6.0.3 on 2026-05-06 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_observationmodel_species'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observationmodel',
            name='img',
            field=models.ImageField(default='', upload_to='observations/'),
        ),
        migrations.AlterField(
            model_name='speciesmodel',
            name='latitude',
            field=models.DecimalField(decimal_places=6, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='speciesmodel',
            name='longitude',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='speciesmodel',
            name='name',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
