# Generated by Django 6.0.3 on 2026-05-06 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_observationmodel_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observationmodel',
            name='latitude',
            field=models.DecimalField(decimal_places=6, max_digits=10),
        ),
        migrations.AlterField(
            model_name='observationmodel',
            name='longitude',
            field=models.DecimalField(decimal_places=6, max_digits=10),
        ),
        migrations.AlterField(
            model_name='observationmodel',
            name='species',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='obsertvations', to='api.speciesmodel', verbose_name='species'),
        ),
    ]
