# Generated by Django 6.0.3 on 2026-05-06 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_observationmodel_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='observationmodel',
            name='description',
            field=models.TextField(max_length=2, null=True),
        ),
    ]
