# Generated by Django 6.0 on 2026-05-07 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_observationmodel_description'),
        ('api', '0007_add_user_city'),
    ]

    operations = [
    ]
