# Generated by Django 6.0.3 on 2026-05-08 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_merge_20260508_0039'),
    ]

    operations = [
        migrations.AddField(
            model_name='observationmodel',
            name='img_thumbnail',
            field=models.ImageField(default='', upload_to='observations/'),
        ),
        migrations.AlterField(
            model_name='observationmodel',
            name='img',
            field=models.ImageField(upload_to='observations/'),
        ),
    ]
