# Generated by Django 6.0.3 on 2026-05-14 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_user_is_verified'),
        ('api', '0009_observationmodel_img_thumbnail_and_more'),
    ]

    operations = [
    ]
