

POST http://127.0.0.1:8000/api/token/ HTTP/1.1
Content-Type: application/json

{
    "username":"admin1",
    "password":"admin1"
}

###
GET  http://127.0.0.1:8000/api/users/me/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzc5MTMyNzE0LCJpYXQiOjE3NzkxMzI0MTQsImp0aSI6IjJiNjcwZThlYzMzODRlMTk4ODlkMGQyMTAzY2EwZWQ4IiwidXNlcl9pZCI6ImM4NjAyYTUxLTVlODMtNDhhYy1iNjE0LWQwYzkzYjIxNWNlMSJ9.GpoWKpbnZYZbFdmqRXzX4RWBrdaqrQoauvlXxwuWtzI

{
    "username":"admin",
    "password":"admin"
}
###
POST http://127.0.0.1:8000/api/users/login/ HTTP/1.1
Content-Type: application/json

{
    "username":"admin",
    "password":"admin"
}
###
POST http://127.0.0.1:8000/api/users/login/ HTTP/1.1
Content-Type: application/json

{
    "username":"admin",
    "password":"admin"
}